[package]
name = "playstation-core"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[features]

[dependencies]
hex = { workspace = true }
itertools = { workspace = true }
md-5 = { workspace = true }
num = { workspace = true }
strum = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }

[dev-dependencies]
itertools = { workspace = true }
sst-r3000 = { workspace = true }
