[package]
name = "playstation"
version.workspace = true
edition.workspace = true
repository.workspace = true

[lints]
workspace = true

[features]

[dependencies]
clap = { workspace = true }
cpal = { workspace = true }
crossbeam = { workspace = true }
eframe = { workspace = true, features = ["persistence", "wgpu", "wayland"] }
egui = { workspace = true, features = ["default_fonts"] }
playstation-core = { workspace = true }
rfd = { workspace = true }
tokio = { workspace = true, features = ["full"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
